name: Fetch Webhook Token

on:
  push:
    branches:
      - main

jobs:
  fetch-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Webhook Token
        id: fetch-token
        run: echo "::set-output name=webhookToken::${{ secrets.WEBHOOKTOKEN }}"
